'use client'

import { useState, useEffect } from 'react'
import { AppShell } from '@/components/layout/AppShell'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { createClient } from '@/lib/supabase/client'
import { useToast } from '@/components/ui/Toast'
import { Skeleton } from '@/components/ui/Skeleton'
import { RefreshCw } from 'lucide-react'
import ReactMarkdown from 'react-markdown'

interface ReportRow {
  id: string
  week_start_date: string
  health_report: string | null
  generated_at: string
}

export default function HealthReportPage() {
  const { toast } = useToast()
  const [loading, setLoading] = useState(true)
  const [regenerating, setRegenerating] = useState(false)
  const [currentRow, setCurrentRow] = useState<ReportRow | null>(null)
  const [pastRows, setPastRows] = useState<ReportRow[]>([])

  useEffect(() => {
    fetchReports()
  }, [])

  async function fetchReports() {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) { setLoading(false); return }

    const { data } = await supabase
      .from('weekly_plans')
      .select('id, week_start_date, health_report, generated_at')
      .eq('user_id', user.id)
      .not('health_report', 'is', null)
      .order('week_start_date', { ascending: false })

    if (data && data.length > 0) {
      setCurrentRow(data[0] as ReportRow)
      setPastRows(data as ReportRow[])
    }
    setLoading(false)
  }

  async function handleRegenerate() {
    setRegenerating(true)
    toast('Generating your health report… this may take up to 60 seconds', 'info')
    try {
      const res = await fetch('/api/plans/report', { method: 'POST' })
      const data = await res.json()
      if (data.success) {
        setCurrentRow((prev) => prev ? { ...prev, health_report: data.report } : prev)
        toast('Health report updated!', 'success')
      } else {
        toast(data.error || 'Failed to generate report', 'error')
      }
    } catch {
      toast('Something went wrong', 'error')
    } finally {
      setRegenerating(false)
    }
  }

  const weekLabel = currentRow
    ? `Week of ${new Date(currentRow.week_start_date + 'T12:00:00Z').toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`
    : ''

  return (
    <AppShell>
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-text-primary">Health Report</h1>
            {weekLabel && <p className="text-xs text-text-secondary mt-0.5">{weekLabel}</p>}
          </div>
          <Button variant="secondary" size="sm" onClick={handleRegenerate} loading={regenerating}>
            <RefreshCw size={14} />
            Regenerate
          </Button>
        </div>

        {/* Past week selector */}
        {pastRows.length > 1 && (
          <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide">
            {pastRows.map((row) => {
              const label = new Date(row.week_start_date + 'T12:00:00Z').toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
              const isCurrent = row.week_start_date === currentRow?.week_start_date
              return (
                <button
                  key={row.id}
                  onClick={() => setCurrentRow(row)}
                  className={`flex-shrink-0 px-3 py-1.5 rounded-full text-xs font-medium border transition-colors ${
                    isCurrent
                      ? 'bg-accent-primary text-white border-accent-primary'
                      : 'bg-white text-text-secondary border-vitalia-border hover:border-accent-primary'
                  }`}
                >
                  {label}
                </button>
              )
            })}
          </div>
        )}

        {loading ? (
          <Card><Skeleton lines={8} /></Card>
        ) : currentRow?.health_report ? (
          <>
            <Card>
              <div className="prose prose-sm max-w-none text-text-primary [&_h2]:text-accent-primary [&_h2]:font-bold [&_h2]:text-lg [&_h2]:mt-6 [&_h2]:mb-3 [&_h2]:pb-2 [&_h2]:border-b [&_h2]:border-accent-primary/30 [&_h3]:font-semibold [&_h3]:text-text-primary [&_h3]:mt-4 [&_h3]:mb-2 [&_p]:text-text-secondary [&_p]:leading-relaxed [&_ul]:text-text-secondary [&_li]:leading-relaxed [&_strong]:text-text-primary [&_strong]:font-semibold">
                <ReactMarkdown>{currentRow.health_report}</ReactMarkdown>
              </div>
            </Card>
            <div className="bg-accent-coral/20 rounded-xl p-4 text-xs text-text-secondary leading-relaxed">
              <strong>Medical Disclaimer:</strong> This report is generated by AI for informational purposes only and should not be considered medical advice. Always consult with a qualified healthcare provider before making changes to your diet, exercise routine, or health regimen.
            </div>
          </>
        ) : (
          <div className="text-center py-16">
            <span className="text-5xl block mb-4">📋</span>
            <h3 className="font-semibold text-text-primary mb-2">No health report yet</h3>
            <p className="text-text-secondary mb-6 text-sm">Generate your personalized health report now</p>
            <Button onClick={handleRegenerate} loading={regenerating}>Generate Now</Button>
          </div>
        )}
      </div>
    </AppShell>
  )
}
